import Link from 'next/link'
import {
  ArrowRight, AlertTriangle, Bot, FileText, Play, Radio, Quote,
  CheckSquare, UserRound, Swords, Search, BadgeCheck,
} from 'lucide-react'
import PageShell from '@/components/PageShell'
import LogoMarquee from '@/components/LogoMarquee'
import AuditCTA from '@/components/AuditCTA'
import NewsletterSignup from '@/components/NewsletterSignup'
import SignalReport from '@/components/SignalReport'
import { CALENDLY_URL } from '@/lib/site'

export const metadata = {
  title: 'Stick & Grow | Content Marketing Your Sales Team Can Actually Use',
  description:
    'A content operation that reports to sales every week: what we published, who engaged, and which accounts to call. Founder POV, competitive intelligence, SEO and AEO, and customer proof, run with AI where it wins and humans where it counts.',
  alternates: { canonical: 'https://stickandgrow.co' },
}

const TRAPS = [
  {
    title: 'Trap 1: The Reporting Gap',
    text: 'Your content report measures impressions, reach and followers. Your sales team measures deals. Nobody has ever connected the two, so content stays a cost you justify rather than a channel you invest in.',
  },
  {
    title: 'Trap 2: The Sameness Machine',
    text: 'Everything published in your category now comes from the same sources, in the same structure, generated by the same tool. Your buyer cannot tell you apart, so they decide on price.',
  },
  {
    title: 'Trap 3: The One-Person Function',
    text: 'You have a writer, or an SEO contractor, or a founder posting between calls. Each is one quarter of a content operation. The gaps between them are where the pipeline leaks out.',
  },
]

const AI_WINS = [
  'Competitive content gap analysis across every player in your category',
  'Mapping the questions and prompts your buyers actually search',
  'Finding where you are absent from AI answers and who gets cited instead',
  'Pulling patterns out of forty customer calls in an afternoon',
  'First-pass drafts built strictly from your own material',
]

const HUMAN_WINS = [
  'Deciding what is worth making at all, and what to kill',
  'Your point of view, your nuance, and the opinions worth defending',
  'Editing for taste, rhythm and the things that make writing readable',
  'Story structure, so a case study lands instead of listing facts',
  'Strategy, sequencing, and knowing when the data is pointing somewhere dumb',
]

const INPUTS = [
  {
    Icon: UserRound,
    label: '01',
    title: 'Founder POV',
    text: 'Your expertise, your nuance, and the arguments that win sales calls. Extracted from you in working sessions, never invented on your behalf.',
  },
  {
    Icon: Swords,
    label: '02',
    title: 'Competitive intelligence',
    text: 'What everyone in your category publishes, what they rank for, and the gaps none of them have filled. We aim at the space rather than the crowd.',
  },
  {
    Icon: Search,
    label: '03',
    title: 'SEO and AEO',
    text: 'Getting found in search, and getting cited inside the AI assistants where more of your buyers now start. Two different disciplines, both required.',
  },
  {
    Icon: BadgeCheck,
    label: '04',
    title: 'Proof',
    text: 'Case studies, testimonials and customer results, written so a skeptical buyer can verify the claim rather than take your word for it.',
  },
]

// Advisory work from Dan's own consulting practice, kept deliberately short
// and skewed to B2B SaaS. Not Stick & Grow engagements: see the bio label.
const CONSULTED_FOR = ['Ahrefs', 'The Hustle', 'Lemon.io', 'ReCart', 'UserLeap']

export default function Home() {
  return (
    <PageShell>
      {/* --- 1. HERO --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black flex flex-col items-center text-center">
        <div className="inline-block border-2 border-black px-3 py-1 text-xs font-black uppercase tracking-widest mb-8 bg-[#cc01ff] text-white -rotate-1 font-mono">
          For Founder-Led B2B SaaS
        </div>

        <h1 className="text-[clamp(2rem,8vw,3rem)] md:text-5xl lg:text-7xl xl:text-8xl font-black mb-10 tracking-tighter uppercase mx-auto max-w-6xl flex flex-col items-center">
          <span className="block mb-2 md:whitespace-nowrap">Turn your content</span>
          <span className="block md:whitespace-nowrap">
            into{' '}
            <span className="inline-block bg-[#00ead9] px-2 pb-1 border-2 border-black -rotate-1 relative top-[-4px]">
              pipeline.
            </span>
          </span>
        </h1>

        <p className="text-xl font-bold mb-12 text-gray-700 max-w-3xl mx-auto leading-relaxed">
          We run the whole content operation and report to your sales team every week: what we published, who engaged with it, and which accounts are worth calling. Not impressions. Names.
        </p>

        {/* VSL placeholder */}
        <div className="w-full max-w-4xl relative mb-16 group">
          <div className="aspect-video bg-gray-100 border-[3px] border-black shadow-[16px_16px_0px_0px_rgba(0,0,0,1)] flex items-center justify-center cursor-pointer relative overflow-hidden transition-all group-hover:shadow-[20px_20px_0px_0px_#cc01ff]">
            <div className="absolute top-4 left-4 flex gap-2">
              <div className="w-3 h-3 rounded-full bg-black" />
              <div className="w-3 h-3 rounded-full bg-black" />
            </div>
            <div className="absolute bottom-4 left-4 right-4 h-2 bg-black/10 rounded-full border border-black overflow-hidden">
              <div className="w-1/3 h-full bg-[#cc01ff]" />
            </div>

            <div className="w-24 h-24 bg-[#00ead9] border-[3px] border-black rounded-full flex items-center justify-center transition-transform group-hover:scale-110 group-hover:bg-[#cc01ff]">
              <Play fill="black" size={40} className="ml-2" />
            </div>
          </div>

          <div className="absolute -bottom-6 -right-6 bg-[#e0fcf9] border-2 border-black p-3 text-sm font-black rotate-3 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] z-20 hidden md:block font-mono">
            Watch: How content becomes pipeline (2 Min)
          </div>
        </div>

        <div className="flex flex-col md:flex-row items-center gap-6 w-full max-w-4xl justify-center">
          <Link
            href="/case-study-creation"
            className="bg-black text-white px-8 py-5 text-lg md:text-xl font-black shadow-[8px_8px_0px_0px_#cc01ff] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-flex items-center justify-center gap-3 w-full md:w-auto uppercase"
          >
            Start With A Case Study <ArrowRight size={24} />
          </Link>
          <Link
            href="/content-engine"
            className="bg-white text-black border-[3px] border-black px-8 py-5 text-lg md:text-xl font-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-flex items-center justify-center gap-3 w-full md:w-auto uppercase"
          >
            See The Content Engine
          </Link>
        </div>

        <div className="bg-yellow-200 border-2 border-black p-4 -rotate-1 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] text-left w-full md:max-w-sm mt-10">
          <span className="font-black uppercase text-sm border-b-2 border-black pb-1 mb-2 block font-mono">The Promise:</span>
          <span className="font-bold text-sm">Your first account list reaches sales inside <span className="underline decoration-black decoration-4">30 days</span>.</span>
        </div>
      </section>

      {/* --- 2. CLIENT LOGOS --- */}
      <LogoMarquee />

      {/* --- 3. THE PROBLEM --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-red-50">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-center gap-3 mb-8">
            <AlertTriangle className="text-red-500" size={32} />
            <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter text-center">
              Nobody Can Tell You If It Worked
            </h2>
          </div>

          <p className="text-center font-bold text-xl mb-12 text-gray-700 max-w-3xl mx-auto">
            You are spending on content and cannot say what it produced. That is rarely a writing problem. Usually it is one of these:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
            {TRAPS.map((trap, i) => (
              <div
                key={i}
                className={`bg-white border-2 border-black p-6 shadow-[6px_6px_0px_0px_#ff4d4f] flex flex-col ${i === 1 ? 'rotate-1' : '-rotate-1'}`}
              >
                <h3 className="text-xl font-black mb-4 uppercase text-red-600">{trap.title}</h3>
                <p className="font-bold text-gray-700 leading-relaxed text-sm">{trap.text}</p>
              </div>
            ))}
          </div>

          <div className="text-center bg-white border-2 border-black p-6 rotate-1 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] max-w-3xl mx-auto">
            <p className="text-xl font-black uppercase tracking-tighter">
              Content should report to sales the way every other revenue channel does. Ours does, every week.
            </p>
          </div>
        </div>
      </section>

      {/* --- 3. THE ARGUMENT: WHERE AI WINS, WHERE PEOPLE DO --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-white">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <div className="inline-block border-2 border-black px-3 py-1 text-xs font-black uppercase tracking-widest mb-6 bg-[#cc01ff] text-white -rotate-1 font-mono">
              How The Work Gets Done
            </div>
            <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-4">
              AI Made Content Free. It Did Not Make It Good.
            </h2>
            <p className="text-lg font-bold text-gray-600 max-w-3xl mx-auto leading-relaxed">
              Producing content stopped being the hard part. The hard part is knowing what to make, where a machine genuinely beats a person, and where it quietly destroys the thing you are paying for. Agencies tend to pick a side. The judgment is the job.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="border-[3px] border-black p-8 bg-gray-100 -rotate-1 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
              <div className="flex items-center gap-3 mb-5">
                <Bot className="text-[#cc01ff]" size={30} />
                <h3 className="text-2xl font-black uppercase tracking-tight">Where we point AI</h3>
              </div>
              <p className="font-bold text-sm text-gray-500 mb-5 font-mono uppercase tracking-wide">
                Volume, recall and pattern-finding
              </p>
              <ul className="space-y-3">
                {AI_WINS.map((item, i) => (
                  <li key={i} className="flex items-start gap-3 font-bold text-gray-700 text-sm leading-relaxed">
                    <CheckSquare className="text-black shrink-0 mt-0.5" size={18} /> {item}
                  </li>
                ))}
              </ul>
            </div>

            <div className="border-[3px] border-black p-8 bg-[#e0fcf9] rotate-1 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
              <div className="flex items-center gap-3 mb-5">
                <Quote className="text-[#cc01ff]" size={30} />
                <h3 className="text-2xl font-black uppercase tracking-tight">Where we put people</h3>
              </div>
              <p className="font-bold text-sm text-gray-600 mb-5 font-mono uppercase tracking-wide">
                Taste, judgment and everything that decides
              </p>
              <ul className="space-y-3">
                {HUMAN_WINS.map((item, i) => (
                  <li key={i} className="flex items-start gap-3 font-bold text-gray-700 text-sm leading-relaxed">
                    <CheckSquare className="text-black shrink-0 mt-0.5" size={18} /> {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* --- 4. THE FOUR INPUTS --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-[#f4f4f5]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-4">
              Four Inputs, One Operation
            </h2>
            <p className="text-lg font-bold text-gray-600 max-w-2xl mx-auto">
              Most companies have one of these and a gap where the other three should be.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {INPUTS.map((item, i) => (
              <div
                key={i}
                className={`border-[3px] border-black bg-white p-6 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] flex flex-col ${i % 2 === 0 ? 'rotate-1' : '-rotate-1'}`}
              >
                <div className="text-[10px] font-black uppercase tracking-widest text-[#cc01ff] mb-4 font-mono">
                  {item.label}
                </div>
                <item.Icon className="mb-4 text-gray-400" size={32} />
                <h3 className="text-xl font-black mb-3 uppercase tracking-tight">{item.title}</h3>
                <p className="font-bold text-gray-600 text-sm leading-relaxed">{item.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* --- 5. THE WEEKLY RECEIPT --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-white">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <div className="inline-block border-2 border-black px-3 py-1 text-xs font-black uppercase tracking-widest mb-6 bg-black text-white -rotate-1 font-mono">
              The Weekly Receipt
            </div>
            <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-4">
              What Your Sales Team Gets On Friday
            </h2>
            <p className="text-lg font-bold text-gray-600 max-w-3xl mx-auto leading-relaxed">
              Every week we hand over the accounts that engaged, what they engaged with, and how warm they are. This is the part that makes the rest of it accountable, and it is the reason the argument stops being about impressions.
            </p>
          </div>

          <SignalReport />
        </div>
      </section>

      {/* --- 6. OFFER ONE: CASE STUDIES --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-[#f4f4f5]">
        <div className="max-w-6xl mx-auto">
          <div className="border-[3px] border-black bg-white shadow-[12px_12px_0px_0px_#cc01ff]">
            <div className="border-b-[3px] border-black bg-black text-white px-6 py-3 flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <FileText size={20} className="text-[#00ead9]" />
                <span className="font-black uppercase tracking-wider text-sm font-mono">Offer 01</span>
              </div>
              <span className="font-mono text-[10px] md:text-xs uppercase tracking-widest text-gray-300">Start Here</span>
            </div>

            <div className="p-8 md:p-12">
              <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-4">Case Study Creation</h2>
              <p className="text-xl font-bold text-gray-700 max-w-3xl mb-8 leading-relaxed">
                The proof your customers already gave you, written down properly. One engagement, one finished asset, and a fast answer to whether this changes how your deals close.
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 mb-10 max-w-4xl">
                {[
                  'We interview your customers, so you do not have to chase them.',
                  'We find the number that actually moved, not a vague percentage.',
                  'We write it so a skeptical buyer can verify every claim.',
                  'You get an asset your sales team will genuinely send.',
                ].map((line, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <CheckSquare className="text-[#cc01ff] shrink-0 mt-1" size={20} />
                    <span className="font-bold text-gray-700">{line}</span>
                  </div>
                ))}
              </div>

              <Link
                href="/case-study-creation"
                className="bg-black text-white px-8 py-4 text-lg font-black shadow-[6px_6px_0px_0px_#00ead9] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-flex items-center gap-3 uppercase"
              >
                How Case Studies Work <ArrowRight size={20} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* --- 7. OFFER TWO: CONTENT ENGINE --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-white">
        <div className="max-w-6xl mx-auto">
          <div className="border-[3px] border-black bg-white shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]">
            <div className="border-b-[3px] border-black bg-[#00ead9] px-6 py-3 flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <Radio size={20} className="text-black" />
                <span className="font-black uppercase tracking-wider text-sm font-mono">Offer 02</span>
              </div>
              <span className="font-mono text-[10px] md:text-xs uppercase tracking-widest text-black/60">The Core System</span>
            </div>

            <div className="p-8 md:p-12">
              <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-4">The Content Engine</h2>
              <p className="text-xl font-bold text-gray-700 max-w-3xl mb-8 leading-relaxed">
                The whole operation, run for you. A 90-day sprint that installs all four inputs, the publishing rhythm, and the weekly reporting line into your sales team.
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 mb-10 max-w-4xl">
                {[
                  'Research, writing, search and proof running as one system.',
                  'Built from your calls and your positions, never from a prompt.',
                  'Every week we hand you the accounts that engaged, by name.',
                  'You keep the library, the tagging and the voice guides.',
                ].map((line, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <CheckSquare className="text-[#cc01ff] shrink-0 mt-1" size={20} />
                    <span className="font-bold text-gray-700">{line}</span>
                  </div>
                ))}
              </div>

              <Link
                href="/content-engine"
                className="bg-black text-white px-8 py-4 text-lg font-black shadow-[6px_6px_0px_0px_#cc01ff] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-flex items-center gap-3 uppercase"
              >
                How The Engine Works <ArrowRight size={20} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* --- 8. FOUNDER BIO --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-[#fdfdfd] flex flex-col md:flex-row gap-12 items-center">
        <div className="w-64 h-80 bg-white border-[3px] border-black p-3 pb-12 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] -rotate-3 shrink-0 flex flex-col relative hover:rotate-0 transition-transform mx-auto md:mx-0">
          <div className="absolute -top-4 left-1/2 -translate-x-1/2 w-16 h-8 bg-[#00ead9]/40 border border-black/20 backdrop-blur-sm -rotate-2 z-10" />
          <div className="flex-1 border-2 border-black overflow-hidden bg-gray-100 relative">
            <img src="/founder.png" alt="Dan McDermott" className="w-full h-full object-cover grayscale contrast-125" />
            <div
              className="absolute inset-0 opacity-[0.15] mix-blend-overlay"
              style={{ backgroundImage: 'radial-gradient(#000 1px, transparent 1px)', backgroundSize: '4px 4px' }}
            />
          </div>
          <div className="pt-4 text-center font-black uppercase text-sm italic">
            Dan McDermott
            <br />
            <span className="text-[10px] text-[#cc01ff] not-italic tracking-widest font-mono">FOUNDER</span>
          </div>
        </div>

        <div>
          <Quote className="text-[#cc01ff] mb-4" size={32} />
          <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tighter mb-6">Why I built this.</h2>
          <p className="text-lg font-bold text-gray-700 leading-relaxed mb-4">
            Over the last 20 years I have been a CMO, built in-house content teams from the ground up, and served as Head Copy Coach at CopywritingCourse.com. I have watched the cost of producing decent content fall to roughly zero, and I have watched most of the industry respond by producing more of it.
          </p>
          <p className="text-lg font-bold text-gray-700 leading-relaxed">
            That was the wrong answer. The right one is knowing what is worth making, using machines for the work they are genuinely better at, and putting experienced people everywhere taste actually decides the outcome. Then proving it weekly to the only audience that matters, which is your sales team.
          </p>

          {/* Labelled separately from the client marquee: these were advisory
              engagements of Dan's, not Stick & Grow builds. */}
          <div className="mt-8 border-2 border-black bg-white p-5 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] -rotate-1 inline-block">
            <div className="text-[10px] font-black uppercase tracking-widest text-[#cc01ff] mb-3 font-mono">
              Consulted For
            </div>
            <p className="font-black uppercase text-sm md:text-base tracking-tight leading-relaxed">
              {CONSULTED_FOR.join(' \u00b7 ')}
            </p>
          </div>
        </div>
      </section>

      {/* --- 9. FREE AUDIT --- */}
      <AuditCTA />

      {/* --- 10. NEWSLETTER --- */}
      <NewsletterSignup />

      {/* --- 11. FINAL CTA --- */}
      <section className="p-8 md:p-20 text-center bg-[#00ead9] relative border-b-[3px] border-black">
        <h2 className="text-3xl md:text-5xl lg:text-6xl font-black uppercase tracking-tighter mb-8 mt-4 max-w-4xl mx-auto">
          Stop reporting impressions. Start reporting{' '}
          <span className="bg-black text-white px-4 py-1 inline-block -rotate-2">accounts.</span>
        </h2>
        <p className="font-bold text-lg text-black/70 max-w-2xl mx-auto mb-10">
          Book a roadmap session. We will look at what you are already sitting on, where the gaps are, and what the first 90 days would actually put in front of your sales team.
        </p>
        <a
          href={CALENDLY_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="bg-white text-black px-8 py-4 text-lg md:px-12 md:py-6 md:text-2xl font-black border-[3px] border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-block uppercase"
        >
          Book A Roadmap Session
        </a>
      </section>
    </PageShell>
  )
}
