import Link from 'next/link'
import {
  ArrowRight, AlertTriangle, Bot, FileText, Radio, Sparkles,
  CheckSquare, Quote, Repeat,
} from 'lucide-react'
import PageShell from '@/components/PageShell'
import AuditCTA from '@/components/AuditCTA'
import NewsletterSignup from '@/components/NewsletterSignup'
import { CALENDLY_URL } from '@/lib/site'

export const metadata = {
  title: 'Stick & Grow | Content Engines Built On Proof, Not How-To',
  description:
    'Anyone with an AI subscription can write the how-to. Only you have the proof. Stick & Grow builds proof-led content engines for founder-led B2B SaaS: customer case studies and a weekly founder-visibility system that produces trackable pipeline.',
  alternates: { canonical: 'https://stickandgrow.co' },
}

const TRAPS = [
  {
    title: 'Trap 1: The Sameness Machine',
    text: "You publish a solid how-to. So does every competitor, pulled from the same sources, in the same structure, generated by the same tool. Your buyer can't tell you apart, so they decide on price.",
  },
  {
    title: 'Trap 2: The Ghostwriter Gap',
    text: "You hire an agency to “do content”. What comes back is competent and completely generic. It reads like your category wrote it, not like your company did.",
  },
  {
    title: 'Trap 3: Proof Locked In Your Head',
    text: "Your best material is sitting in customer calls, in your CRM, and in your own memory. It has never been written down, so it never works for you while you sleep.",
  },
]

export default function Home() {
  return (
    <PageShell>
      {/* --- 1. HERO --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black flex flex-col items-center text-center">
        <div className="inline-block border-2 border-black px-3 py-1 text-xs font-black uppercase tracking-widest mb-8 bg-[#cc01ff] text-white -rotate-1 font-mono">
          For Founder-Led B2B SaaS
        </div>

        <h1 className="text-[clamp(1.75rem,7vw,3rem)] md:text-5xl lg:text-7xl font-black mb-10 tracking-tighter uppercase mx-auto max-w-6xl flex flex-col items-center">
          <span className="block mb-2 md:whitespace-nowrap">Anyone can write</span>
          <span className="block mb-2 md:whitespace-nowrap">the how-to. Only you</span>
          <span className="block md:whitespace-nowrap">
            have the{' '}
            <span className="inline-block bg-[#00ead9] px-2 pb-1 border-2 border-black -rotate-1 relative top-[-4px]">
              proof.
            </span>
          </span>
        </h1>

        <p className="text-xl font-bold mb-12 text-gray-700 max-w-3xl mx-auto leading-relaxed">
          Your competitor has the same AI subscription you do. The guides, the listicles, the ultimate explainers: all of it is now a commodity anyone can produce in a minute. What nobody can produce is what your customers did with you, and what you have learned building the thing. We turn that into content that sells.
        </p>

        {/* The thesis, shown rather than claimed */}
        <div className="w-full max-w-4xl grid grid-cols-1 md:grid-cols-2 gap-6 mb-12 text-left">
          <div className="border-2 border-black bg-gray-100 p-6 -rotate-1 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-2 mb-4">
              <Bot className="text-gray-400" size={24} />
              <h2 className="text-lg font-black uppercase text-gray-500">Anyone can write this</h2>
            </div>
            <ul className="space-y-2 font-bold text-sm text-gray-500 font-mono">
              <li>&ldquo;What is [category]? A complete guide&rdquo;</li>
              <li>&ldquo;10 best practices for [problem]&rdquo;</li>
              <li>&ldquo;[Competitor] vs [Competitor]: which wins?&rdquo;</li>
              <li>&ldquo;5 trends shaping [industry] in 2026&rdquo;</li>
            </ul>
          </div>

          <div className="border-2 border-black bg-[#e0fcf9] p-6 rotate-1 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles className="text-[#cc01ff]" size={24} />
              <h2 className="text-lg font-black uppercase">Only you can write this</h2>
            </div>
            <ul className="space-y-2 font-bold text-sm text-gray-700 font-mono">
              <li>&ldquo;How Northwind cut onboarding from 6 weeks to 9 days&rdquo;</li>
              <li>&ldquo;The pricing model we tried for a year and killed&rdquo;</li>
              <li>&ldquo;What 40 customer calls taught us about churn&rdquo;</li>
              <li>&ldquo;Why we said no to our biggest prospect&rdquo;</li>
            </ul>
          </div>
        </div>

        <div className="flex flex-col md:flex-row items-center gap-6 w-full max-w-4xl justify-center">
          <Link
            href="/case-study-creation"
            className="bg-black text-white px-8 py-5 text-lg md:text-xl font-black shadow-[8px_8px_0px_0px_#cc01ff] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-flex items-center justify-center gap-3 w-full md:w-auto uppercase"
          >
            Start With A Case Study <ArrowRight size={24} />
          </Link>
          <Link
            href="/content-engine"
            className="bg-white text-black border-[3px] border-black px-8 py-5 text-lg md:text-xl font-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-flex items-center justify-center gap-3 w-full md:w-auto uppercase"
          >
            See The Content Engine
          </Link>
        </div>
      </section>

      {/* --- 2. THE PROBLEM --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-red-50">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-center gap-3 mb-8">
            <AlertTriangle className="text-red-500" size={32} />
            <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter text-center">
              Everyone Sounds The Same Now
            </h2>
          </div>

          <p className="text-center font-bold text-xl mb-12 text-gray-700 max-w-3xl mx-auto">
            You are not losing because your content is bad. You are losing because it is indistinguishable from everyone else&rsquo;s. Usually it is one of these:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
            {TRAPS.map((trap, i) => (
              <div
                key={i}
                className={`bg-white border-2 border-black p-6 shadow-[6px_6px_0px_0px_#ff4d4f] flex flex-col ${i === 1 ? 'rotate-1' : '-rotate-1'}`}
              >
                <h3 className="text-xl font-black mb-4 uppercase text-red-600">{trap.title}</h3>
                <p className="font-bold text-gray-700 leading-relaxed text-sm">{trap.text}</p>
              </div>
            ))}
          </div>

          <div className="text-center bg-white border-2 border-black p-6 rotate-1 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] max-w-3xl mx-auto">
            <p className="text-xl font-black uppercase tracking-tighter">
              The fix is not more content. It is writing down the things only you can say, and putting them where your buyers already look.
            </p>
          </div>
        </div>
      </section>

      {/* --- 3. THE THESIS --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-white">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <div className="inline-block border-2 border-black px-3 py-1 text-xs font-black uppercase tracking-widest mb-6 bg-[#cc01ff] text-white -rotate-1 font-mono">
              The Argument
            </div>
            <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-4">
              Proof Is The Part That Can&rsquo;t Be Copied
            </h2>
            <p className="text-lg font-bold text-gray-600 max-w-2xl mx-auto">
              It runs in two directions, and a serious company needs both.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="border-[3px] border-black p-8 bg-[#e0fcf9] -rotate-1 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
              <div className="text-[10px] font-black uppercase tracking-widest text-[#cc01ff] mb-3 font-mono">
                Looking Backward
              </div>
              <h3 className="text-2xl md:text-3xl font-black uppercase tracking-tight mb-4">
                What your customers already did
              </h3>
              <p className="font-bold text-gray-700 leading-relaxed mb-6">
                Results you can point at. The number, the before, the after, and the name of a person who will vouch for it. This is the proof a buyer can go and check for themselves, which is exactly why it works.
              </p>
              <Link href="/case-study-creation" className="font-black uppercase text-sm inline-flex items-center gap-2 border-b-4 border-[#cc01ff] pb-1 hover:text-[#cc01ff] transition-colors">
                Case Study Creation <ArrowRight size={16} />
              </Link>
            </div>

            <div className="border-[3px] border-black p-8 bg-yellow-100 rotate-1 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
              <div className="text-[10px] font-black uppercase tracking-widest text-[#cc01ff] mb-3 font-mono">
                Looking Forward
              </div>
              <h3 className="text-2xl md:text-3xl font-black uppercase tracking-tight mb-4">
                What you know right now
              </h3>
              <p className="font-bold text-gray-700 leading-relaxed mb-6">
                You, visible every week, with real opinions and lessons pulled from the calls you are actually on. Nobody can generate this, because it has not happened to anyone else. This is proof you are still earning.
              </p>
              <Link href="/content-engine" className="font-black uppercase text-sm inline-flex items-center gap-2 border-b-4 border-[#cc01ff] pb-1 hover:text-[#cc01ff] transition-colors">
                The Content Engine <ArrowRight size={16} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* --- 4. OFFER ONE: CASE STUDIES --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-[#f4f4f5]">
        <div className="max-w-6xl mx-auto">
          <div className="border-[3px] border-black bg-white shadow-[12px_12px_0px_0px_#cc01ff]">
            <div className="border-b-[3px] border-black bg-black text-white px-6 py-3 flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <FileText size={20} className="text-[#00ead9]" />
                <span className="font-black uppercase tracking-wider text-sm font-mono">Offer 01</span>
              </div>
              <span className="font-mono text-[10px] md:text-xs uppercase tracking-widest text-gray-300">
                Start Here
              </span>
            </div>

            <div className="p-8 md:p-12">
              <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-4">
                Case Study Creation
              </h2>
              <p className="text-xl font-bold text-gray-700 max-w-3xl mb-8 leading-relaxed">
                The proof your customers already gave you, written down properly. One engagement, one finished asset, and a fast answer to whether this changes how your deals close.
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 mb-10 max-w-4xl">
                {[
                  'We interview your customers, so you do not have to chase them.',
                  'We find the number that actually moved, not a vague percentage.',
                  'We write it so a skeptical buyer can verify every claim.',
                  'You get an asset your sales team will genuinely send.',
                ].map((line, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <CheckSquare className="text-[#cc01ff] shrink-0 mt-1" size={20} />
                    <span className="font-bold text-gray-700">{line}</span>
                  </div>
                ))}
              </div>

              <Link
                href="/case-study-creation"
                className="bg-black text-white px-8 py-4 text-lg font-black shadow-[6px_6px_0px_0px_#00ead9] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-flex items-center gap-3 uppercase"
              >
                How Case Studies Work <ArrowRight size={20} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* --- 5. OFFER TWO: CONTENT ENGINE --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-white">
        <div className="max-w-6xl mx-auto">
          <div className="border-[3px] border-black bg-white shadow-[12px_12px_0px_0px_rgba(0,0,0,1)]">
            <div className="border-b-[3px] border-black bg-[#00ead9] px-6 py-3 flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <Radio size={20} className="text-black" />
                <span className="font-black uppercase tracking-wider text-sm font-mono">Offer 02</span>
              </div>
              <span className="font-mono text-[10px] md:text-xs uppercase tracking-widest text-black/60">
                The Core System
              </span>
            </div>

            <div className="p-8 md:p-12">
              <h2 className="text-3xl md:text-5xl font-black uppercase tracking-tighter mb-4">
                The Content Engine
              </h2>
              <p className="text-xl font-bold text-gray-700 max-w-3xl mb-8 leading-relaxed">
                You, visible every week, with a trackable pipeline underneath it. A 90-day sprint that installs the whole system: what gets published, who reacts to it, and which accounts your sales team should call.
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-4 mb-10 max-w-4xl">
                {[
                  'LinkedIn, newsletter, and blog running on one weekly rhythm.',
                  'Built from your calls and your positions, never from a prompt.',
                  'Every week we hand you the accounts that engaged, by name.',
                  'Founder visibility without you becoming a full-time creator.',
                ].map((line, i) => (
                  <div key={i} className="flex items-start gap-3">
                    <CheckSquare className="text-[#cc01ff] shrink-0 mt-1" size={20} />
                    <span className="font-bold text-gray-700">{line}</span>
                  </div>
                ))}
              </div>

              <Link
                href="/content-engine"
                className="bg-black text-white px-8 py-4 text-lg font-black shadow-[6px_6px_0px_0px_#cc01ff] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-flex items-center gap-3 uppercase"
              >
                How The Engine Works <ArrowRight size={20} />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* --- 6. THE UPGRADE LOGIC --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-[#f4f4f5]">
        <div className="max-w-4xl mx-auto text-center">
          <Repeat className="mx-auto mb-6 text-[#cc01ff]" size={40} />
          <h2 className="text-2xl md:text-4xl font-black uppercase tracking-tighter mb-6">
            Most people start with one case study
          </h2>
          <p className="text-lg font-bold text-gray-700 leading-relaxed max-w-2xl mx-auto">
            Then the question changes. A case study proves the mechanism works: your buyers respond to proof, and your sales team finally has something worth sending. What it cannot do is happen again next month without you. That is the point where founders stop asking whether this works and start asking how to run it every week. That is the engine.
          </p>
        </div>
      </section>

      {/* --- 7. TRACK RECORD --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-white overflow-hidden">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tighter mb-4">
            Run Four Times. Not A Hypothesis.
          </h2>
          <p className="text-lg font-bold text-gray-600 max-w-2xl mx-auto">
            This proof-led play has been built inside four very different organizations, including this one.
          </p>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-5xl mx-auto">
          {[
            { name: 'Copywriting Course', tag: 'Education', color: 'bg-yellow-200' },
            { name: 'Vouris', tag: 'B2B Sales', color: 'bg-[#e0fcf9]' },
            { name: 'Zen Healthcare IT', tag: 'Healthcare', color: 'bg-pink-100' },
            { name: 'Stick & Grow', tag: 'This Agency', color: 'bg-[#00ead9]' },
          ].map((org, i) => (
            <div
              key={i}
              className={`${org.color} border-2 border-black p-6 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] flex flex-col items-center justify-center text-center min-h-[140px] ${i % 2 === 0 ? 'rotate-1' : '-rotate-1'}`}
            >
              <div className="font-black text-base md:text-lg uppercase tracking-tight leading-tight mb-2">
                {org.name}
              </div>
              <div className="text-[10px] font-bold text-gray-600 uppercase font-mono tracking-widest">
                {org.tag}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* --- 8. FOUNDER BIO --- */}
      <section className="relative z-10 p-8 md:p-16 border-b-[3px] border-black bg-[#fdfdfd] flex flex-col md:flex-row gap-12 items-center">
        <div className="w-64 h-80 bg-white border-[3px] border-black p-3 pb-12 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] -rotate-3 shrink-0 flex flex-col relative hover:rotate-0 transition-transform mx-auto md:mx-0">
          <div className="absolute -top-4 left-1/2 -translate-x-1/2 w-16 h-8 bg-[#00ead9]/40 border border-black/20 backdrop-blur-sm -rotate-2 z-10" />
          <div className="flex-1 border-2 border-black overflow-hidden bg-gray-100 relative">
            <img src="/founder.png" alt="Dan McDermott" className="w-full h-full object-cover grayscale contrast-125" />
            <div
              className="absolute inset-0 opacity-[0.15] mix-blend-overlay"
              style={{ backgroundImage: 'radial-gradient(#000 1px, transparent 1px)', backgroundSize: '4px 4px' }}
            />
          </div>
          <div className="pt-4 text-center font-black uppercase text-sm italic">
            Dan McDermott
            <br />
            <span className="text-[10px] text-[#cc01ff] not-italic tracking-widest font-mono">FOUNDER</span>
          </div>
        </div>

        <div>
          <Quote className="text-[#cc01ff] mb-4" size={32} />
          <h2 className="text-3xl md:text-4xl font-black uppercase tracking-tighter mb-6">Why I built this.</h2>
          <p className="text-lg font-bold text-gray-700 leading-relaxed mb-4">
            Over the last 20 years I have been a CMO, built in-house content teams from the ground up, and served as Head Copy Coach at CopywritingCourse.com. I have watched the cost of producing decent how-to content fall to roughly zero, and I have watched the value of it fall with it.
          </p>
          <p className="text-lg font-bold text-gray-700 leading-relaxed">
            What did not fall is the value of a story only one company can tell. I built Stick &amp; Grow because product-obsessed founders keep losing to louder competitors while sitting on proof they never wrote down. You should not have to become a full-time creator to fill your pipeline. You need the things you already know, on the page, where buyers can find them.
          </p>
        </div>
      </section>

      {/* --- 9. FREE AUDIT --- */}
      <AuditCTA />

      {/* --- 10. NEWSLETTER --- */}
      <NewsletterSignup />

      {/* --- 11. FINAL CTA --- */}
      <section className="p-8 md:p-20 text-center bg-[#00ead9] relative border-b-[3px] border-black">
        <h2 className="text-3xl md:text-5xl lg:text-6xl font-black uppercase tracking-tighter mb-8 mt-4 max-w-4xl mx-auto">
          Stop publishing what anyone could write. Start publishing{' '}
          <span className="bg-black text-white px-4 py-1 inline-block -rotate-2">proof.</span>
        </h2>
        <p className="font-bold text-lg text-black/70 max-w-2xl mx-auto mb-10">
          Book a roadmap session. We will look at what proof you are already sitting on, and what it would take to put it to work.
        </p>
        <a
          href={CALENDLY_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="bg-white text-black px-8 py-4 text-lg md:px-12 md:py-6 md:text-2xl font-black border-[3px] border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all inline-block uppercase"
        >
          Book A Roadmap Session
        </a>
      </section>
    </PageShell>
  )
}
